# -*- coding: utf-8 -*-
"""NLP4ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1imnYp2toef5NFJIV0cl2GA6CUsO4mTGG
"""

dicionary2={'the':'DET', 'Koala':'N'}

sentince='the Koala'

for token in sentince.split():
  print(token)

dicionary2={'the':'DET', 'Koala':'N'}

sentince='the Koala'

for token in sentince.split():
  print(token, ':', dicionary2[token])

dicionary2={'the':'DET', 'Koala':'N', 'read':['VB','VBP']}

sentince='read the Koala '

for token in sentince.split():

  print(token,' : ', dicionary2[token])

dicionary={'I':'PONNOUN','a':'DET','book':'N','everyday':'VB','the':'DET', 'Koala':'N', 'read':['VB','VBP']}

sentince='I read a book everyday'

def rules(sentince):
  if('laest' in sentince):
    return 'VB'

for token in sentince.split():
  if isinstance(dicionary[token], list):
    print(token,' : Ambigus', dicionary[token])
  else:
    print(token,' : ', dicionary[token])