# -*- coding: utf-8 -*-
"""NLP7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13PSu-AH5ZSa43Ygfe5ew6RTf84UkNmIg
"""

def student(mark):
  if(mark<60):
    return 'Fail'
  else:
    return 'Pass'

student(80)

input=[90,50,40,100,75]
output=['Pass','Fail','Fail','Pass','Pass']

def learn(input,output,mark):
  return result

input=[18,5,25,20,21,4] #قانون عمر رخصة القيادة
output=['OK','NO','OK','OK','OK','NO']

def learn(input,output,mark):
  return result

#TALK ABOUT ML.. like learn humman .. Important ML >> job machine learning

# we will use libaray https://www.tensorflow.org/ >> from google
# we will use dataset kaggle http://www.kaggle.com/

data=[90,50,40,100,75]
c1=[90,100,75]
c2=[50,40]
def mylearning(data,output):
  return result

# input=[90,50,40,100,75]
input=[19,5,25,20,21,4] #Train by choose neariest neighborhood
# output=['Pass','Fail','Fail','Pass','Pass']
output=['NO','NO','OK','OK','OK','NO']

def learn(input,output,mark):
  return result