# -*- coding: utf-8 -*-
"""NLP1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wDWnSy7OOn1kuGvWbFN-5EL0ublo4chD
"""

import re
tokens='students are happy'
x = re.findall(".*s", tokens)

print(x)

import re
tokens='students are happy'
x = re.findall("h.*", tokens)
print(x)

import re
tokens='students are happy'
x = re.findall("a.*\s", tokens)
print(x)

import nltk
from nltk.stem import *
stemmer = PorterStemmer()
stem1=stemmer.stem('cars')
stem2=stemmer.stem('Playing')
print(stem1)
print(stem2)

sentince='I love my cars'
tokens=sentince.split(' ')
print(tokens)
for i in tokens:
  print(i,stemmer.stem(i))