# -*- coding: utf-8 -*-
"""NLP2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k174JRkDzD6o3Pt5J8F5sr1-5ha6NLSM
"""

import re
txt = "My student number is 440011596"
y = re.findall("4.*",txt) #My try
print(y)

x = re.findall("4a*.",txt) #try student XXXXXX
print(x)

#{} repert          [] rang
z = re.findall("4[0-9]{8}",txt)   #this is true لاننا نبحث عن نمط
print(z)
# print(x[0][0:-3],x[1][0:-3])


#for curses
name = "CS450 This is my AI course"
M = re.findall("CS[0-9]{3}",name)
print(M)



txt1= "Dreamful colorful"
t = re.findall("\\b.*ful\\b", txt1)
print(t)


txt2= "a1234@gmail.com   @@gmail@123"
e = re.findall( ".*@gmail.com", txt2)
print(e)

num = "0583903010   0135810000"
y = re.findall("05[0-9]{8}",num) #if 01[0-9]{8}
print(y)

import nltk
from nltk.stem import *
stemmer = PorterStemmer()
stem1=stemmer.stem('cars')
stem2=stemmer.stem('Playing')
print(stem1)
print(stem2)

sentince='I love my cars'
tokens=sentince.split(' ')
print(tokens)
for i in tokens:
  print(i,stemmer.stem(i))

import re 
txt= "Dreamful colorful"
X = re.findall("\\b.*ful\\b", txt)
Z = re.findall(".*ful", txt)
print(X)
print(Z)

def system(name):
  return name+' is postive'
system('Nasser')

import re
txt = "aa"
patt = "^[a-z]$"
i = re.match(patt, txt)
# print(i)
if i == None: print("Not Match")
else: print("yes")

import re 
txt= "The the other then"
X = re.findall("\\b[tT]he\\b", txt)
Z = re.findall(".*[tT]he", txt)
print(X)
print(Z)