# -*- coding: utf-8 -*-
"""NLP9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nQle6f_lMmjFjf-LRCFUc0TiDW9S-uIA
"""

# Week 8 .. on Tuseday .. 20 OCT

# Supervsied learning

input=[90,40,60,10]
output=['Pass','Fail','Pass','Fail']

# Unsupervsied learning

input=[90,40,60,10]

gr1=[90,60]
gr2=[40,10]

# Reinforcement learning