# -*- coding: utf-8 -*-
"""NLP10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19eCDwNq6sQVuQrratz8TUX287n9gfxKS
"""

#  Week 9 on Wed .. 26 OCT

import pandas as pd
import nltk
from nltk.stem.isri import ISRIStemmer
st = ISRIStemmer()
data = pd.read_csv('/content/sample_data/CompanyReviews.csv')

a = [0]*2579
print(a)
# dic[st.stem('ممتاز')]
print(a)

a = [0]*2579
print(a)
print(st.stem('ممتاز'))
print(a)