# -*- coding: utf-8 -*-
"""NLP project1 W9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H9Ald8RRjvoOTJZ-Slma9wX88SrW-ytk
"""

! pip install fastai

import fastai
print(fastai.__version__)

# import nltk #Nautural langauge tool kit اداة معالجة اللغات
# nltk.download('averaged_perceptron_tagger')
# nltk.download('punkt')

import pandas as pd # allow read fael csv(Comma-separated values) and put on column
import nltk
from nltk.stem.isri import ISRIStemmer # استخدمناه عشان يقلل الكلمات و المصفوفة في الديكشنري
st = ISRIStemmer()
data = pd.read_csv('/content/sample_data/CompanyReviews.csv')
# print(data) #me
# print(data.head()) #Dr #Defult head(5)

# I choose 2 column
inputs = data['review_description']
output = data['rating']
print(inputs.head())
print(output.head())

############### Reviw ############
# from NLP 8 > creeat dic ......
# dic={}
# num=0
# for i in input:
#   for token in i.split():
#     if(token in dic.keys()):
#       print(token, 'It has been added', dic[token])
#     else:
#       dic[token]=num
#       num=num+1
#################################

# يعني اني بمر على الجمل كلها وك جملة بفصلها لتوكن
# وبعجين برجع الجملة لأصلها
# to help shourt number of words
def creatDictionary(inputs):
  dic= {}
  num = 0
  for i in inputs:
    i = str(i)
    print()
    for token in i.split():
      # if(token in dic.keys()): #4620 .. try if eimlit stem
      if(st.stem(token) in dic.keys()):
        # print(token, 'It has been added', dic[token])
        pass
      else:
        # dic[token]= num #4620 .. try without stem
        dic[st.stem(token)]= num
        num = num+1
  return dic

dic = creatDictionary(inputs[0:1000])
print(len(dic)) # 2579 words 

# until now we creat dicinary
# after that convort token to number (array)




def convertInputToarray(inputs, dic):
  inputConverted = []
  for i in inputs:
    listofzeros = [0] * len(dic.keys()) #ضرب حجم القاموس اللي عندي # create list contain zoero every index
    i = str(i) # برجع الكلمة لأصلها فتأكد ان الجملة سترينق
    for token in i.split(): #يفصل الكلمات
      if(st.stem(token) in dic.keys()):
        listofzeros[dic[st.stem(token)]] = 1 # اذا موجودة التوكن بيحط مكانه واحد في الليست جملة جملة
    inputConverted.append(listofzeros)
  return inputConverted # 1000 عامود .. row = 2579 # عكست هنا :)

dic = creatDictionary(inputs[0:1000]) # بيرسل االف عنصر ف بيصير الف صف و الاعمدة يساوي عدد الكلمات
print('Words in Dicionary : ',len(dic.keys())) # 2579 words
inputConverted = convertInputToarray(inputs[0:1000],dic) 





# Now can I use nearest neighborhod algorithm

######################### review ######################
import numpy as np
def nearestNeighborAlgrothim(input,output,newinput): 
  diference=[] # عرفت لست
  for i in input:
    diference.append(sum(abs(np.array(i)-np.array(newinput)))) 
  nearestNeighbor =min(diference)
  return output[diference.index(nearestNeighbor)]

##############################################################


print(nearestNeighborAlgrothim(inputConverted[0:1000], output[0:1000], inputConverted[4]))
print(inputs[4], ' Label: ', output[4])


# نخلي المستخدم يدخل الكلمات 
text = input('Enter Text')
convertedText = convertInputToarray([text],dic)
print(convertedText[0]) #output[convertedText[0]]
nearestNeighborAlgrothim(inputConverted[0:1000], output[0:1000], convertedText[0])

a = [0]*2579
print(a)
dic[st.stem('ممتاز')]
# print(a) #بجي لاندكس 77 وبحط مكانه 1 بدل الصفر

# More Words

import pandas as pd # allow read fael csv(Comma-separated values) and put on column
import nltk
from nltk.stem.isri import ISRIStemmer # استخدمناه عشان يقلل الكلمات و المصفوفة في الديكشنري
st = ISRIStemmer()
data = pd.read_csv('/content/sample_data/CompanyReviews.csv')
# print(data) #me
# print(data.head()) #Dr #Defult head(5)

# I choose 2 column
inputs = data['review_description']
output = data['rating']
print(inputs.head())
print(output.head())

############### Reviw ############
# from NLP 8 > creeat dic ......
# dic={}
# num=0
# for i in input:
#   for token in i.split():
#     if(token in dic.keys()):
#       print(token, 'It has been added', dic[token])
#     else:
#       dic[token]=num
#       num=num+1
#################################

# يعني اني بمر على الجمل كلها وك جملة بفصلها لتوكن
# وبعجين برجع الجملة لأصلها
# to help shourt number of words
def creatDictionary(inputs):
  dic= {}
  num = 0
  for i in inputs:
    i = str(i)
    print()
    for token in i.split():
      # if(token in dic.keys()): #4620 .. try if eimlit stem
      if(st.stem(token) in dic.keys()):
        # print(token, 'It has been added', dic[token])
        pass
      else:
        # dic[token]= num #4620 .. try without stem
        dic[st.stem(token)]= num
        num = num+1
  return dic

dic = creatDictionary(inputs[0:10000])
print(len(dic)) # 2579 words 

# until now we creat dicinary
# after that convort token to number (array)




def convertInputToarray(inputs, dic):
  inputConverted = []
  for i in inputs:
    listofzeros = [0] * len(dic.keys()) #ضرب حجم القاموس اللي عندي # create list contain zoero every index
    i = str(i) # برجع الكلمة لأصلها فتأكد ان الجملة سترينق
    for token in i.split(): #يفصل الكلمات
      if(st.stem(token) in dic.keys()):
        listofzeros[dic[st.stem(token)]] = 1 # اذا موجودة التوكن بيحط مكانه واحد في الليست جملة جملة
    inputConverted.append(listofzeros)
  return inputConverted # 1000 عامود .. row = 2579 # عكست هنا :)

dic = creatDictionary(inputs[0:10000]) # بيرسل االف عنصر ف بيصير الف صف و الاعمدة يساوي عدد الكلمات
print('Words in Dicionary : ',len(dic.keys())) # 2579 words
print('')
inputConverted = convertInputToarray(inputs[0:10000],dic) 





# Now can I use nearest neighborhod algorithm

######################### review ######################
import numpy as np
def nearestNeighborAlgrothim(input,output,newinput): 
  diference=[] # عرفت لست
  for i in input:
    diference.append(sum(abs(np.array(i)-np.array(newinput)))) 
  nearestNeighbor =min(diference)
  return output[diference.index(nearestNeighbor)]

##############################################################


print(nearestNeighborAlgrothim(inputConverted[0:10000], output[0:10000], inputConverted[4]))
print(inputs[4], ' Label: ', output[4])
print(inputs[0], ' Label: ', output[0])

# نخلي المستخدم يدخل الكلمات 
text = input('Enter Text')
convertedText = convertInputToarray(text,dic)
print(convertedText[0]) #output[convertedText[0]]
# print(convertedText.append(inputs,output)) #fail try
# print(convertedText.insert(1,text))
nearestNeighborAlgrothim(inputConverted[0:10000], output[0:10000], convertedText[0])

# convertedText [] >> note