# -*- coding: utf-8 -*-
"""NLP learn2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_wQw44o-JkCit2nJy_rRcd6ibjoNFVZi
"""

import pandas as pd
import nltk
from nltk.stem.isri import ISRIStemmer
st = ISRIStemmer()
pd.read_csv('/content/sample_data/SA_Aqar.csv')
# pd.read_csv('/content/sample_data/SA_Aqar.csv', usecols= ['city','district'])

# To dicrip
employees = pd.read_csv("/content/sample_data/SA_Aqar.csv")
# print(Employee.head(5))
employees = employees[["city", "district"]]

pd.read_csv('/content/sample_data/SA_Aqar.csv', usecols= ['city','district'] )